databases:
  - name: flex
    ipAllowList: []
    region: frankfurt
    plan: free

services:
  - type: web
    plan: free
    name: flex
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: supervisord -c supervisord.conf
    region: frankfurt
    envVars:
      - key: API_HASH 
        sync: false
      - key: API_ID 
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: flex 
          property: connectionString
    autoDeploy: false
